### ISSUE TITLE
Na uvodní obrazovce mi aplikace "blika"

### ISSUE THREAD

**Issue by pavelkaste** [covid19cz/erouska-ios#107]
Na úvodní obrazovce, se obrazovka zhasne pokud omylem zakryji prstem senzor přiblížení. Takto obrazovka zhasne pokud je zakrytý, pokud prsty oddělám, obrazovka se rozsvítí. (Všiml jsem si toho náhodou, ale dělat by to podle mě nemělo....)

![e-rouska](https://user-images.githubusercontent.com/64483649/80945483-33dad880-8dec-11ea-98ea-dbc3a351eeb5.jpg)

iPhone 7 (32GB)

**Comment by ddmus** [comment]
Tohle je ve skutecnosti feature.  Az uzivatel projde registraci a skenovani je aktivni, tak se proximity senzor spolu z nezhasinanim obrazovky pouziva pro lepsi skenovani na popredi. Pokud je appka na pozadi, skenovani je mene ucinne. Je to prave detailne popsane na hlavni screene po registraci.

**Comment by ddmus** [comment]
Ten proximy senzor se ale nastavuje jednou v cele appce, nejde to zapnout az po registraci.

**Comment by pavelkaste** [comment]
aha to jsem netušil, omlouvám se, díky a ať se daří.
