### ISSUE TITLE
Validace zahranicnich telefonich cisel

### ISSUE THREAD

**Issue by Kioshi** [covid19cz/erouska-ios#111]
Validace nefunguje správně, nevím jestli je to designová chyba (uživatel by měl být vyzván k zadání pouze českého číslo), nebo technická.

Pro Dánske číslo, lze zadat spravnou předvolbu +45 bez námitek aplikace, ale při zadání čísla samotneho XX XX XX XX, nelze zvalidovat protože se očekává 9-ti ciferné číslo.

**Comment by augard** [comment]
@Kioshi Nemate jeste strasi 1.0, verzi od 1.1 jde napsat delsi cislo nez 9 znaku.

**Comment by Kioshi** [comment]
Mám verzi 1.1
Problém není ze číslo je moc dlouhé, ale krátké (8 znaků)
![5063D7AF-3BE7-4AEB-8DEB-39C4EFBDDA84](https://user-images.githubusercontent.com/4405687/81394398-29894900-9122-11ea-92ab-253375776dc4.png)

**Comment by augard** [comment]
V budouci verzi uz nebude registrace pres telefoni cislo, zaviram.
