### ISSUE TITLE
implementace Apple COVID-19 exposure API

### ISSUE THREAD

**Issue by emx0r** [covid19cz/erouska-ios#113]
Zvazuje se aplikaci prepracovat tak aby pouzivala oficialni Apple COVID-19 Expose API?
Prijde me ze soucasne reseni ma na iOS problemy s detekci kdyz bezi na pozadi, velmi casto nenfunguje, a neustale mit otevrenou aplikaci je neprakticke.

Podle poslednich informaci ma byt erouska take soucasti oficialni chytre karanteny takze by to mel byt kandidat prave na toto reseni? Myslim ze Apple prave povoluje pouze jednu aplikaci na zemi - asi by davalo smyl kdyby to byla prave erouska?

**Comment by augard** [comment]
Ano, pracuje se na tom. eRouska dostala pred par dny opravneni k pouziti. Bez toho nebylo ani mozno vyvyjet.

**Comment by emx0r** [comment]
diky

**Comment by panva** [comment]
> Ano, pracuje se na tom. eRouska dostala pred par dny opravneni k pouziti. Bez toho nebylo ani mozno vyvyjet.

Blizime se?

**Comment by augard** [comment]
Koncept je pripraveny, problem je ted s predelanim systemu, ktere budou pouzivat higiena. Jeste to chvili potrva, bohuzel aplikace je jen na zacatku retezce.

**Comment by augard** [comment]
Aplikace s A/G protokolem je venku.
