### ISSUE TITLE
zaznam kontaktu na pozadi nefunguje

### ISSUE THREAD

**Issue by flapee** [covid19cz/erouska-ios#114]
iOS 13.4.1 iP 8, ver 1.1
-Kdyz upozadenu iOS eRousku polozim vedle Android eRousky:
android rozpozna blizke setkani, iOS bohuzel az po prepnuti aplikace do popredi

**Comment by augard** [comment]
Tak bohuzel funguje bluetooth na iOS, se zavrenym telefonem se vypne BT scannovani. Bude vyreseno s prechodem na  Apple/Google ExposureNotification framework.
