### ISSUE TITLE
Neplatné tel cislo

### ISSUE THREAD

**Issue by michalblaha** [covid19cz/erouska-ios#116]
1. 7. 2020
Po více než 100 dnech dobrovolníci ze zdravotnické linky s volbou 2 pod celostátní infolinkou 1212 ukončují činnost. Řešili tisíce dotazů veřejnosti po celý průběh epidemie covid-19. Zdravotnická linka nyní přechází přímo pod oddělení pro veřejnost Ministerstva zdravotnictví s novým jednotným číslem 224 972 222. Jde o oficiální linku pro veřejnost ke všem zdravotnickým tématům, nejen koronavirovým.
V erousce je stále puvodni 1212
![041E08A9-D492-494D-9C68-00A3686EDD73](https://user-images.githubusercontent.com/367276/87087351-3960fe80-c233-11ea-8e37-93793ab9f953.png)
![Uploading 81B29EB0-5929-42B5-ADEC-006DF8B6437D.png…]()

**Comment by augard** [comment]
Bude odstraneno ve verzi 1.1

**Comment by mkj-is** [comment]
Vidím, že je číslo v aplikaci již odstraněné, ale issue je stále otevřená.

Tské jsem si všimnul, že v App Store je neaktuální screenshot a tím pádem i chybná informace v něm.

Bylo by určitě vhodné následující screenshot aktualizovat nebo odstranit.

![image](https://user-images.githubusercontent.com/708312/93384768-91386900-f865-11ea-98a8-4981ed4a0a14.jpeg)

**Comment by augard** [comment]
Screenshot uz je aktualni
