### ISSUE TITLE
Verze 1.2 nelze spustit

### ISSUE THREAD

**Issue by emx0r** [covid19cz/erouska-ios#153]
Po aktualizaci na verzi 1.2 aplikace nelze nadale pouzit.
Po spusteni ukazuje spashscreen ze je k dispozici novejsi aktualizace, ta ale samozrejme neexistuje

**Comment by czervenka** [comment]
+1 … stejný problém

**Comment by czervenka** [comment]
Update: Po [vynuceném ukončení](https://support.apple.com/cs-cz/HT201330) se aplikace spustila normálně (obrazovka vynucující aktualizaci zmizela).

**Comment by augard** [comment]
Ano, problem byl v nasi praci s remote configuraci, bohuzel jsme si neuvedomily, ze se aktualizuje jen po spusteni aplikace. Proto par procentum uzivatelu se zobrazila obrazovka o pozadavku na novy update i kdyz jeste neni k dispozici.
