### ISSUE TITLE
Jak bude erouska 2.0 fungovat s Exposure Notifications Express systemem?

### ISSUE THREAD

**Issue by emx0r** [covid19cz/erouska-ios#161]
Nejde o report issue, spise o dotaz, protoze ted uplne presne nechapu jak bude erouska 2.0 fungovat s Exposure Notifications Express systemem.

https://9to5mac.com/2020/09/01/covid-19-exposure-ios-13-7-built-in/

Zda se, ze tato funkce nevyzaduje zadne externi aplikace. V podstate se stat jen opt-inuje k pouziti express systemu kde zdeli sve podminky a zbytek uz potom funguje klasicky v OS. Melo by to byt kompatibilni i mezi iOS <-> Android.

Muj dotaz tedy je, prinasi v tomto smeru erouska 2.0 nejakou vyhodu proc ji mit nainstalovanou?
Popripade nebude dochazet k hadani integrovane funkce a externi aplikace?

Diky

**Comment by augard** [comment]
Aplikace je venku.

**Comment by matronator** [comment]
> Aplikace je venku.

That’s nice and all, but it doesn’t really answer the question.
