### ISSUE TITLE
eRouška visí ve stavu "pozastavená"

### ISSUE THREAD

**Issue by ondrejmirtes** [covid19cz/erouska-ios#168]
Dobrý den,
takto u mě vypadá eRouška z App Storu:

![IMG_2252](https://user-images.githubusercontent.com/104888/93516291-2309aa00-f92a-11ea-973a-c84c9a33739b.PNG)

Kliknutí na Spustit eRoušku nic nedělá. Při počátečním průchodu jsem vše povolil.

**Comment by ondrejmirtes** [comment]
Restart iPhonu nepomohl.

**Comment by augard** [comment]
Pomuze smazani rousky a znovu nainstalovani, mely jsme uz podobny report na twitteru. Uzivatel aktivoval system sledovani pres jinou aplikaci a potom to deaktivoval.

**Comment by ondrejmirtes** [comment]
Diky, pomohlo, ale jsem si jisty, ze zadnou jinou aplikaci jsem nezkousel :)

**Comment by augard** [comment]
Super, urcite se na to kouknem, mate uz iOS 14?

**Comment by augard** [comment]
(necham to otevrene pro dalsi vyzkum)

**Comment by ondrejmirtes** [comment]
jj mám. Každopádně to může být nějaká chyba systému :)

**Comment by ondrejmirtes** [comment]
Aplikace nejdřív napsala "eRouška je aktivní", pak jsem se jí proklikával, šel do Odeslat data apod., a samo se to pozastavilo a nešlo to už přepnout. Každopádně po reinstalu mi to už jde.

**Comment by CrazyMuffin** [comment]
Měl jsem stejný problém, taky na iOS 14.

Workaround bez reinstalace:

1. Otevřít permissions settings pro aplikaci
2. Zakázat a povolit všechna relevantní práva.
3. Restartovat aplikaci

**Comment by fidraj** [comment]
Potvrzuji ten samy problem. Workaround od @CrazyMuffin nefungoval, musel jsem reinstalovat. Toto muze byt pro radu uzivatelu problem.

**Comment by tomassliz** [comment]
Mně se app dostala do tohoto stavu na iOS 14 po otevření Exposure Notification v Settings. Třeba to pomůže.

**Comment by augard** [comment]
Muzu se zeptat na vase telefony, ktery typ mate?

**Comment by CrazyMuffin** [comment]
@augard iPhone 11

**Comment by fidraj** [comment]
iPhone Xs

**Comment by tomassliz** [comment]
iPhone 8

**Comment by vojtagrec** [comment]
Mně to na iPhone 8 Plus s iOS 13 fungovalo, že je appka “seknutá” jsem si všiml až na iOS 14. Práva měla appka přidělená, ale mám dojem, že v nastavení “Oznámení o kontaktech s nákazou” nebyla nastavená aktivní oblast. Poté, co jsem ji nastavil (pravda, pro jistotu vypnul/zapnul všechna ostatní oprávnění - ad @CrazyMuffin) už to zase funguje. Možná je to to stejné, co popisuje @tomassliz...

**Comment by ondrejmirtes** [comment]
iPhone Xs

**Comment by augard** [comment]
Jeste nekdo aktivoval eRousku na iOS 13 a potom aktualizoval na iOS 14, diky.

**Comment by ondrejmirtes** [comment]
Jaký měl být přesně stav na iOS 14 betách předtím, než vyšla eRouška 2.0? Viděl jsem, že v některých zemích iOS 13.7 a potenciálně bety umožnily trackování bez stažení zvláštní aplikace, ale nikdy mi to nešlo v ČR zapnout. Možná jde o symptom stejného problému?

Každopádně eRoušku 2.0 jsem stahoval až na iOS 14 GM.

**Comment by CrazyMuffin** [comment]
Aplikaci jsem stahoval úplně poprvé až ve verzi 2.0 na iOS14 a problém nastal prakticky ihned po prvním startu.

**Comment by augard** [comment]
@ondrejmirtes V betach to bylo ruzny, ze zacatku to tam uplne chybelo. To trackovani bez aplikace je jen pro US, cele je to nepochopeni toho ze chtel jen A/G pomoct s tim, ze to tam nikdo nechtel pouzit. Take to potrebuje propojeni na mistni hygienu, mistni backend atd.

**Comment by augard** [comment]
Kazdopadne se zuzilo na iOS 14. Zatim nikdo nenapsal jiny system, diky.

**Comment by tomassliz** [comment]
> Jeste nekdo aktivoval eRousku na iOS 13 a potom aktualizoval na iOS 14, diky.

Já měl na iOS 13 aktivní nativní Apple řešení. eRousku jsem instaloval až na iOS 14.

**Comment by augard** [comment]
@tomassliz Ok, tak jeste nevylucujem uplne taky problem s prechodem na iOS 14, apple reseni je == eRouska, jen si nebyla prirazena aplikace a jelo to naprazdno.

**Comment by augard** [comment]
Take nemecka aplikace ma stejny problem: https://www.coronawarn.app/en/faq/#no_risk_update_ios14

**Comment by meuges** [comment]
problematika u instalovane appky na iOS13, nasledne prechod systemu na iOS14, je potreba zrusit prava a zpatky nastavit. Jinak erouska2.0 je zasekla a nic. Chyba asi v prenosu a hlavne iOS14 je novy system, ktery nebyl vytvareny s necim jako erouska, tudiz ac ma erouska moznosti, iOS14 cista instalace o tom nevi.

**Comment by marcajs** [comment]
> Kazdopadne se zuzilo na iOS 14. Zatim nikdo nenapsal jiny system, diky.

Mel jsem stejny problem na iOS13.  Workaround od @CrazyMuffin tez nefungoval, vyresila to reinstalace appky. Nyni po updatu na iOS14 appka stale funguje. Resp. pise, ze eRouska je aktivni (i po restartu).

**Comment by augard** [comment]
Posun v issue je takovy, ze nas Apple informoval o chybe v iOS 14.0 a 14.1, ktera chybu znovu zpusobuje. Hlavne pri obnove zalohy na novy iPhone (12). Alespon ted to berou jako chybu u sebe a opravy to v dalsich verzich iOS.
