### ISSUE TITLE
Rizikové setkání - nepřesná informace?

### ISSUE THREAD

**Issue by ondrejmirtes** [covid19cz/erouska-ios#169]
Dobrý den,
čerstvě po instalaci mi sekce Rizikové setkání píše "V posledních 14 dnech nebyla ve vaš blízkosti žádná osoba s potvrzeným onemocněním COVID-19".

Je tato informace přesná, tedy používá aplikace data, která "potichu" posledních 14 dní sbíral systém? Nebo je to číslo 14 hardcodované a tudíž nepřesné? Mělo by se možná namísto toho používat `min(počet dní od instalace, 14)`...

**Comment by augard** [comment]
Aplikace nepozna presne jak dlouho uz mate aktivovany system. Ale system zapisuje maximalne 14 dni zpet.

**Comment by augard** [comment]
(muzete treba pouzivat par dni nemeckou aplikaci a pak prejit zpet na ceskou)

**Comment by ondrejmirtes** [comment]
eRouška by mohla pracovat s datem, jak dlouho je nainstalovaná ona sama?

**Comment by augard** [comment]
To ano. Zamyslime se jak to lepe sformulovat aby to hned po spusteni nevypadalo zlastne, diky.

**Comment by lukas-kurka** [comment]
> To ano. Zamyslime se jak to lepe formulovat, aby to hned po spusteni nevypadalo zlastne, diky.

Při diskuzi o jiné formulaci navrhuji zrevidovat i “.. nebyla ve vaší blízkosti žádná osoba..” na něco ve smyslu “...eRouška/systém nezaregistroval žádnou osobu..” protože to, že systém takovou událost neeviduje neznamá, že se tak nestalo. Původní formulace může navozovat falešný pocit bezpečí.

**Comment by augard** [comment]
Obrazovky budou mit novou podobu ve verzi 2.2
