### ISSUE TITLE
Angličtina vs čeština v 2.1

### ISSUE THREAD

**Issue by igorkulman** [covid19cz/erouska-ios#170]
S iOS v angličtine mám v 2.1 aplikáciu v češtine ale jedna obrazovka je celá v angličtine. Vyzerá to celkom komicky:

<img width="414" alt="signal-2020-09-17-205529" src="https://user-images.githubusercontent.com/4746070/93573395-5d5d6080-f997-11ea-8da9-c3017a4475c8.png">

Ak explicitne nastavím, aby sa aplikácia ukazovala v češtine, tak sa tá anglická obrazovka zmení na českú ale jej menu položka ostane stále v angličtine (Risky encounters).

Trochu nechápem, prečo sa aplikácia tvári, že podporuje angličtinu, keď to tak nie je (a ako to vôbec prešlo cez review). Je to len matúce.

**Comment by augard** [comment]
Aplikace se nestihla cela prelozit vcas, tento konkretni text uz by nemel byt anglicky. Anglictina bude venku pravdepodobne pristi tyden.
