### ISSUE TITLE
Aktualizace “Aktuálně” pomocí pull-to-refresh

### ISSUE THREAD

**Issue by Kaspik** [covid19cz/erouska-ios#171]
Nechal jsem od včera zapnutou eRoušku na pozadí a chtěl se v ní dnes podívat na Aktuálni data. Bohužel jediný způsob jak data aktualizovat bylo restartovat aplikaci. Bylo by možné data aktualizovat automaticky nebo přidat pull-to-refresh? :)

**Comment by augard** [comment]
Je vyreseno v aktualizaci, ktera je prave ve schvalovani. Data se aktualizuji jen parkrat dene, proto tam nechceme davat manualni aktualizaci pres pull to refresh.
