### ISSUE TITLE
Podpora iPad mini 5

### ISSUE THREAD

**Issue by bedla** [covid19cz/erouska-ios#173]
Dobry den, 
kamarad ma iPad mini 5 (https://en.wikipedia.org/wiki/IPad_Mini_(5th_generation)) a podle vseho splnuje HWove moznost provozovat eRousku, kterou by moc chtel mit spustenou. Ve zdrojaku jsem nasel, ze je IFovano jen na iPhony, ale odkazovany link nerika nic o tom, ze by to s exposure protocolem nemelo pracovat. Mohl bych poprosit o provereni? Prosel jsem dokumentaci na https://covid19.apple.com/contacttracing a prijde mi, ze se tam nikde nepise, ze iPady jsou nepodporovany... nebo mi neco uniklo (nejsem Apple uzivatel/programator).
Dekuji
Ivos

**Comment by augard** [comment]
iPad a iPod touch neni podporovan na urovni iOS, s tim bohuzel nemuzeme nic delat.

**Comment by bedla** [comment]
aha diky... ja to nikde explicitne receny nenasel, tak se radeji ptam.
