### ISSUE TITLE
Počet kontaktů

### ISSUE THREAD

**Issue by Vykook** [covid19cz/erouska-ios#175]
Bylo by fajn kdyby aplikace zobrazovala kolik setkání zaznamenala. Člověk by měl alespoň rámcový přehled jestli potkává lidi s erouškou a nebo jede "na prázdno".

**Comment by augard** [comment]
Neni to technicky mozne, Apple/Google protokol nam nedovoluje cist data co zaznamenava. Jen jednou za cas je vyhodnotit.
