### ISSUE TITLE
Beh aplikace v background

### ISSUE THREAD

**Issue by augard** [covid19cz/erouska-ios#18]
Na starsich telefonech iPs - 6s, je roportovano nefunknost vysilani na pozadi.

**Comment by pitbulls1** [comment]
iPhone 7 taky jsem spozoroval ze to nenajde nic. Naposledy co mám je 6 a 7.5 víc nic. Nefunguje to jak bych předpokládal. A mít rozvicen mobil? Stejně by se mi zhasl sám. Radši si počkám na aktualizaci iOSu a tam to budu mít už rovnou a tohle budu moct smazat, když to nedělá co by mělo.

**Comment by augard** [comment]
Jen aktualizace iOS nepomuze, na to budete potrebovat jeste aplikace. V CR to bude eRouska. Bohuzel jak to funguje ted je jedina moznost, jine nam iOS nedovoluje.

**Comment by kutakmir** [comment]
@augard můžeš prosím rozvést tento issue? Na novějších iPhones to tedy funguje?

V dokumentaci:
https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html#//apple_ref/doc/uid/TP40013257-CH7-SW7

Píšou:
```
the Core Bluetooth framework allows your app to run in the background to perform certain Bluetooth-related tasks. While your app is in the background you can still discover and connect to peripherals, and explore and interact with peripheral data.
```

Jsou tam nějaké nevyřčené restrikce? Klasicky backgroundTaskem si můžeme podržet appku naživu, ale didDiscover se nezavolá, když dám vyhledávat periferie.

Jak jste toto debuggovali a na co jste přišli?

**Comment by augard** [comment]
Kdyz zhasnes display prestane iOS scannovat, i kdyz mas nastaveny background. Je to divny, ale tak to funguje.

**Comment by kutakmir** [comment]
@augard kontaktovali jste ohledně tohoto issue Apple? Je na to nějaký ticket v jejich systému?

**Comment by augard** [comment]
S prechodem na apple/google protokolem to uz neni nutne resit

**Comment by kutakmir** [comment]
Řešit to má smysl pro jiné využití než COVID. To, že nesouhlasí dokumentace je časté úskalí iOS periferií. To aby to člověk zjišťoval stylem pokus-omyl.
