### ISSUE TITLE
Nelze aktivovat na iPhone SE (starší iOS)

### ISSUE THREAD

**Issue by lzap** [covid19cz/erouska-ios#183]
Ačkoli mi App Store povolil na tomto starším mobilu instalaci starší verze, všechny pokusy o ověření telefonního čísla selhávají s messageboxem. Je to škoda, je to poměrně oblíbený model.

Nešlo by udělat build kde by to číslo už nebylo vyžadováno, jako u té nejnovější verze? Uprímně to číslo na hygienu byl pro mě show-stopper, nainstaloval jsem si na svém telefonu až tu verzi 2.1 kde to už není.

FYI na iPhone 11 vše funguje skvěle, díky.

**Comment by augard** [comment]
Na starsich verzich byl aktivovat pred nekolika dny "force update" ktery zobrazi obrazovku ze je nutne aktualizovat iOS. Pripadne ze se omlouvame a vas telefon neni bohuzel uz podporovany.
