### ISSUE TITLE
Přidat čas při zobrazení podezření na rizikové setkání

### ISSUE THREAD

**Issue by sadovsf** [covid19cz/erouska-ios#184]
Bylo by dobré kromě datumu kdy došlo k rizikovému setkání zobrazit alespoň přibližnou hodinu kdy k němu došlo. Objevují se informace o false positive od lidí kteří daný den tvrdí že nikam nešli daný den. Myslím že uvedení alespoň hrubé časové značky spolu s datumem by lidem pomohlo dohledat nebo si vzpomenout kde v tu dobu byly. Data tam pro to jsou k dispozici pokud si dobře pamatuji z kódu.

**Comment by augard** [comment]
Dobry den, to bohuzel neni technicky mozne, API od Apple/Google to nedovoluje.

**Comment by sadovsf** [comment]
Ah i see now, `ENExposureInfo` contains only approximation up to date no further. For others who run into this idea hare is source:

https://developer.apple.com/documentation/exposurenotification/enexposureinfo
And specifically date property:
https://developer.apple.com/documentation/exposurenotification/enexposureinfo/3583713-date
