### ISSUE TITLE
Signup - eRouška - navigation item - large title - automatic nefunguje

### ISSUE THREAD

**Issue by zrzka** [covid19cz/erouska-ios#47]
Název eRouška je velký a při posunutí obrazovky se nezmenší a nezajede do navbaru. Na iPhone SE si toho moc nepočtu, protože to zabírá dost místa.

Vidím

<img width="432" alt="Screen Shot 2020-04-11 at 12 14 30" src="https://user-images.githubusercontent.com/1084172/79041194-1ac87880-7bee-11ea-914a-6dc141233016.png">

Čekal bych

<img width="432" alt="Screen Shot 2020-04-11 at 12 14 52" src="https://user-images.githubusercontent.com/1084172/79041201-2156f000-7bee-11ea-8ac0-d34bdff870f7.png">

**Comment by beny** [comment]
Opraveno v rámci #56.
