### ISSUE TITLE
iPhone SE: Ověření - useknutý text

### ISSUE THREAD

**Issue by zrzka** [covid19cz/erouska-ios#48]
Text je useknutý a nejde scrollovat, takže vlastně nevím co mi chcete sdělit.

<img width="432" alt="Screen Shot 2020-04-11 at 12 16 03" src="https://user-images.githubusercontent.com/1084172/79041215-48152680-7bee-11ea-8d12-c48aca03cd3a.png">

**Comment by beny** [comment]
Opraveno v rámci #56.
