### ISSUE TITLE
Soubor db.csv by měl být v temporaryDirectory

### ISSUE THREAD

**Issue by zrzka** [covid19cz/erouska-ios#50]
Jelikož jde o dočasný soubor, pouze pro účely odeslání, proč je v `.documentDirectory` a ne v [temporaryDirectory](https://developer.apple.com/documentation/foundation/nsfilemanager/1642996-temporarydirectory?language=objc)?

**Comment by IntelBohdan** [comment]
https://github.com/covid19cz/erouska-ios/pull/54
