### ISSUE TITLE
K zamyšlení - tab Moje data

### ISSUE THREAD

**Issue by zrzka** [covid19cz/erouska-ios#57]
Celkově mi ta obrazovka přijde taková „přetechnizovaná“. Myslím pro běžné smrtelníky.

<img width="432" alt="Screen Shot 2020-04-12 at 12 28 57" src="https://user-images.githubusercontent.com/1084172/79066626-b377fa80-7cb9-11ea-8fef-876fedf2c017.png">

## Úvodní text

_Vyhledávání ostatních zařízení ve vašem okolí je na telefonech iPhone při zhasnutém displeji méně účinné._

* Aplikace pro iPhone, netřeba zdůrazňovat **na telefonech iPhone**.
* Věta říká, že je to méně účinné, tj. říká co nefunguje, ale neříká jak to zlepšit.

Osobně bych to přepsal na něco jako:

_Pro účinnější vyhledávání ostatních zařízení doporučujeme nezamykat telefon a nechat aplikaci spuštěnou._

Případně celé vyhodil neb se to duplikuje s textem na tabu eRouška (_Na místech s větší koncentrací lidí nechte aplikaci spuštěnou při ..._).

## Tabulka

* Kdo z nich ví co je RSSI?
* Kdo z nich ví co je ID?
* Zbývá Datum & Čas, k čemu to těm lidem je?

Předpokládám, že ten důvod je: ukázat lidem co sdílejí. IMHO lepší by bylo:

* Dát tam počet všech setkání
* Dát tam počet blízkých setkání
* Nad tlačítko Odeslat data dát další vysvětlení co to udělá

## Tlačítko Odeslat data

* Zdůraznil bych anonymizovaná
* Nad to tlačítko přidal vysvětlující text

Neboli bych udělal něco na tento způsob:

<img width="432" alt="Screen Shot 2020-04-12 at 13 04 43" src="https://user-images.githubusercontent.com/1084172/79067268-634f6700-7cbe-11ea-891b-0041acfe092e.png">

Nezapomenout, že ...

* spousta lidí se bojí sdílet data,
* je potřeba zdůraznit slovo anonymizované,
* místo RSSI, ID, ... jim ukázat jen počet setkání, nestrašit je informacemi, kterým nerozumí („Co je RSSI?“ Není to náhodou místo kde jsem byl? „Co je ID?“ Není to identifikátor nějakého místa?)

Just my $0.02 ...

**Comment by Kobzol** [comment]
Souhlasím s většinou návrhů, nicméně ten počet setkání je problematický, protože jedno zařízení má spoustu různých ID. Takže pak by uživatelů doma seděli vedle 1 telefonu a v tabulce by viděli 20 setkání a ptali by se, co to je za blbost. Ve skutečnosti přesně tohle číslo už na té obrazovce dříve bylo a později jsme ho odstranili :)

**Comment by zrzka** [comment]
Pravda je, že nikde není definováno co znamená „setkání“ - ani já jsem to tolik nezkoumal abych zjistil co to přesně vyjadřuje.

V tom případě se ty čísla dají nahradit jedním úplně obecným jako „Počet záznamů“ (technicky počet záznamů v DB) a nebo je odstranit úplně.

Nebyl jsem u diskuse ohledně UI, ... a tak to berte spíš jako komentář někoho kdo si to spustil a zamyslel se pohledem běžného smrtelníka.

**Comment by augard** [comment]
S google/apple protokolem to uz nebude nastesti mozne, odstrani se.
