### ISSUE TITLE
Nemoznost kliknout na odkaz prekryty prechodem nad buttony

### ISSUE THREAD

**Issue by michalsrutek** [covid19cz/erouska-ios#80]
Uzivatel nemuze kliknout na odkazy, ktere se nachazi pod vrstvou, ktera se stara o smooth prechod na pomezi textu/buttonu.

AFAIK se to tyka 

- uvodni obrazovky, kde je posledni odkaz Vice o auditech a Podminky
- obrazovky s tel. c., kde je odkaz Podminky zpracovani (na iPhone SE s vyjetou klavesnici)

**Comment by augard** [comment]
Muzes to znovu vyzkouset?

**Comment by michalsrutek** [comment]
Funguje 👍
