### ISSUE TITLE
Chybí .DS_Store v .gitignore

### ISSUE THREAD

**Issue by zrzka** [covid19cz/erouska-ios#86]
Přidejte pls `.DS_Store` do `.gitignore`:

```
**/.DS_Store
```

Stačí otevřít projekt v Xcode a už tam jsou.

**Comment by michalsrutek** [comment]
@zrzka mel jsi nejnovejsi verzi projektu? Uz jsem pridaval v ramci #66 🤔

**Comment by zrzka** [comment]
@michalsrutek koukám do historie a máš recht. Přidal jsem to, protože mi Tower ukazoval několik `.DS_Store` souborů. Netuším proč mi to ukazoval, protože tvůj `**/.DS_Store` tam už byl. Nějaké zatmění slunce proběhlo a je to tam teď 2x - na začátku a na konci. Buď se to může revertnout a nebo nechat, na funkci živočicháře to nemá vliv.
