### ISSUE TITLE
Rozbity markdown v Napovede

### ISSUE THREAD

**Issue by michalsrutek** [covid19cz/erouska-ios#93]
Nahled rozbiteho:
![Simulator Screen Shot - iPhone 11 - 2020-04-18 at 12 24 41](https://user-images.githubusercontent.com/35694712/79635171-aa7ea180-816f-11ea-818c-802352a5f017.png)

Nahled funkcniho v Moje data
![Simulator Screen Shot - iPhone 11 - 2020-04-18 at 12 24 23](https://user-images.githubusercontent.com/35694712/79635176-b36f7300-816f-11ea-976c-53c353ac686d.png)

**Comment by ddmus** [comment]
Tohle je na backendu. Android ma na devu stejny nesmysl. Na produkci je to ok.

**Comment by michalsrutek** [comment]
Opraveno. Zaviram.
